version: "3.9"
services:
  app:
    build: "."
    container_name: first-front
    restart: "no"        
    volumes:
      - ./:/app
    environment:
      - TZ=America/Sao_Paulo
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.dev
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    expose:
      - 3000
networks:
  default:
    name: first-network